rpki: T3252: bugfix AttributeError
Traceback (most recent call last):
  File "/opt/vyatta/sbin/vyos-update-rpki-cache.py", line 79, in <module>
    create_cache(config, cache)
  File "/opt/vyatta/sbin/vyos-update-rpki-cache.py", line 21, in create_cache
    new_privkey = c.return__value(base_path + "cache {0} ssh private-key-file".format(cache))
AttributeError: 'Config' object has no attribute 'return__value'

(cherry picked from commit 7c7ae83434bcfae6cef07eab162ecfe20abd8c8f)